"""Configurable scenario definitions for unstructured traffic research."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Mapping


@dataclass(frozen=True, slots=True)
class ScenarioBlueprint:
    slug: str
    name: str
    description: str
    base_env_id: str
    layout: str
    traffic_density: tuple[float, float]
    aggressiveness_mix: Mapping[str, float]
    hazard_density: tuple[float, float]
    pedestrian_frequency: tuple[float, float]
    pothole_density: tuple[float, float]
    visibility: tuple[float, float]
    friction: tuple[float, float]
    obstacle_density: tuple[float, float]
    lane_count: tuple[int, int] = (2, 4)
    duration: tuple[int, int] = (45, 90)
    tags: tuple[str, ...] = ()
    metadata: Mapping[str, float | str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class ScenarioConfig:
    slug: str
    name: str
    description: str
    base_env_id: str
    layout: str
    env_config: dict
    traffic_density: float
    aggressiveness_mix: dict[str, float]
    hazard_density: float
    pedestrian_frequency: float
    pothole_density: float
    obstacle_density: float
    visibility: float
    friction: float
    lane_count: int
    duration: int
    tags: tuple[str, ...]
    metadata: dict[str, float | str]


def _preset(
    slug: str,
    name: str,
    description: str,
    base_env_id: str,
    layout: str,
    *,
    traffic_density: tuple[float, float],
    aggressiveness_mix: Mapping[str, float],
    hazard_density: tuple[float, float],
    pedestrian_frequency: tuple[float, float],
    pothole_density: tuple[float, float],
    visibility: tuple[float, float],
    friction: tuple[float, float],
    obstacle_density: tuple[float, float],
    lane_count: tuple[int, int] = (2, 4),
    duration: tuple[int, int] = (45, 90),
    tags: tuple[str, ...] = (),
    metadata: Mapping[str, float | str] | None = None,
) -> ScenarioBlueprint:
    return ScenarioBlueprint(
        slug=slug,
        name=name,
        description=description,
        base_env_id=base_env_id,
        layout=layout,
        traffic_density=traffic_density,
        aggressiveness_mix=aggressiveness_mix,
        hazard_density=hazard_density,
        pedestrian_frequency=pedestrian_frequency,
        pothole_density=pothole_density,
        visibility=visibility,
        friction=friction,
        obstacle_density=obstacle_density,
        lane_count=lane_count,
        duration=duration,
        tags=tags,
        metadata=dict(metadata or {}),
    )


SCENARIO_LIBRARY: dict[str, ScenarioBlueprint] = {
    "dense_informal_intersection": _preset(
        "dense_informal_intersection",
        "Dense informal intersection",
        "High-density multi-agent intersection with weak right-of-way compliance.",
        "intersection-v0",
        "intersection",
        traffic_density=(0.72, 1.00),
        aggressiveness_mix={"normal": 0.25, "aggressive": 0.24, "erratic": 0.22, "opportunistic": 0.18, "defensive": 0.07, "conservative": 0.04},
        hazard_density=(0.08, 0.20),
        pedestrian_frequency=(0.18, 0.45),
        pothole_density=(0.02, 0.12),
        visibility=(0.75, 1.00),
        friction=(0.85, 1.00),
        obstacle_density=(0.04, 0.14),
        tags=("junction", "dense", "informal"),
    ),
    "aggressive_merge_traffic": _preset(
        "aggressive_merge_traffic",
        "Aggressive merge traffic",
        "Fast closing vehicles with high merge pressure and limited courtesy.",
        "merge-v0",
        "merge",
        traffic_density=(0.60, 0.95),
        aggressiveness_mix={"aggressive": 0.38, "opportunistic": 0.26, "normal": 0.16, "erratic": 0.12, "defensive": 0.04, "conservative": 0.04},
        hazard_density=(0.03, 0.10),
        pedestrian_frequency=(0.00, 0.04),
        pothole_density=(0.01, 0.08),
        visibility=(0.80, 1.00),
        friction=(0.85, 1.00),
        obstacle_density=(0.02, 0.08),
        tags=("merge", "aggressive"),
    ),
    "chaotic_roundabout": _preset(
        "chaotic_roundabout",
        "Chaotic roundabout",
        "Dense roundabout interactions with opportunistic entry and exit behavior.",
        "roundabout-v0",
        "roundabout",
        traffic_density=(0.58, 0.90),
        aggressiveness_mix={"normal": 0.22, "aggressive": 0.18, "erratic": 0.18, "opportunistic": 0.28, "defensive": 0.08, "conservative": 0.06},
        hazard_density=(0.04, 0.12),
        pedestrian_frequency=(0.06, 0.20),
        pothole_density=(0.01, 0.08),
        visibility=(0.75, 1.00),
        friction=(0.80, 1.00),
        obstacle_density=(0.02, 0.09),
        tags=("roundabout", "dense"),
    ),
    "pedestrian_swarm_crossing": _preset(
        "pedestrian_swarm_crossing",
        "Pedestrian swarm crossing",
        "Frequent crossing events with coordinated and hesitant pedestrians.",
        "intersection-v0",
        "crosswalk",
        traffic_density=(0.35, 0.70),
        aggressiveness_mix={"normal": 0.20, "defensive": 0.18, "conservative": 0.18, "opportunistic": 0.18, "aggressive": 0.14, "erratic": 0.12},
        hazard_density=(0.05, 0.15),
        pedestrian_frequency=(0.40, 0.95),
        pothole_density=(0.00, 0.06),
        visibility=(0.80, 1.00),
        friction=(0.85, 1.00),
        obstacle_density=(0.01, 0.06),
        tags=("pedestrian", "crosswalk"),
    ),
    "motorcycle_lane_splitting": _preset(
        "motorcycle_lane_splitting",
        "Motorcycle lane splitting",
        "Narrow high-speed motorcycles weaving through slower traffic.",
        "highway-v0",
        "corridor",
        traffic_density=(0.48, 0.88),
        aggressiveness_mix={"motorcycle_bias": 1.0, "aggressive": 0.24, "opportunistic": 0.22, "normal": 0.20, "erratic": 0.18, "defensive": 0.08, "conservative": 0.08},
        hazard_density=(0.02, 0.10),
        pedestrian_frequency=(0.00, 0.02),
        pothole_density=(0.02, 0.12),
        visibility=(0.82, 1.00),
        friction=(0.85, 1.00),
        obstacle_density=(0.01, 0.05),
        tags=("corridor", "motorcycle"),
    ),
    "sudden_obstacle_emergence": _preset(
        "sudden_obstacle_emergence",
        "Sudden obstacle emergence",
        "Dynamic obstacles appear ahead of the ego under moderate traffic.",
        "highway-v0",
        "corridor",
        traffic_density=(0.30, 0.65),
        aggressiveness_mix={"normal": 0.28, "aggressive": 0.18, "opportunistic": 0.18, "defensive": 0.14, "erratic": 0.12, "conservative": 0.10},
        hazard_density=(0.10, 0.28),
        pedestrian_frequency=(0.00, 0.04),
        pothole_density=(0.01, 0.10),
        visibility=(0.70, 1.00),
        friction=(0.85, 1.00),
        obstacle_density=(0.10, 0.24),
        tags=("corridor", "dynamic_obstacle"),
    ),
    "pothole_avoidance_corridor": _preset(
        "pothole_avoidance_corridor",
        "Pothole avoidance corridor",
        "Straight corridor with severe pothole clusters and avoidance decisions.",
        "highway-v0",
        "corridor",
        traffic_density=(0.20, 0.55),
        aggressiveness_mix={"normal": 0.20, "conservative": 0.18, "defensive": 0.20, "opportunistic": 0.16, "aggressive": 0.14, "erratic": 0.12},
        hazard_density=(0.15, 0.35),
        pedestrian_frequency=(0.00, 0.03),
        pothole_density=(0.30, 0.75),
        visibility=(0.75, 1.00),
        friction=(0.82, 1.00),
        obstacle_density=(0.02, 0.08),
        tags=("corridor", "pothole"),
    ),
    "informal_overtaking_traffic": _preset(
        "informal_overtaking_traffic",
        "Informal overtaking traffic",
        "Frequent opportunistic overtakes with inconsistent following behavior.",
        "highway-v0",
        "corridor",
        traffic_density=(0.45, 0.85),
        aggressiveness_mix={"opportunistic": 0.30, "aggressive": 0.20, "normal": 0.18, "erratic": 0.14, "defensive": 0.10, "conservative": 0.08},
        hazard_density=(0.04, 0.12),
        pedestrian_frequency=(0.00, 0.03),
        pothole_density=(0.01, 0.08),
        visibility=(0.80, 1.00),
        friction=(0.85, 1.00),
        obstacle_density=(0.02, 0.08),
        tags=("corridor", "overtaking"),
    ),
    "stop_and_go_urban_congestion": _preset(
        "stop_and_go_urban_congestion",
        "Stop-and-go urban congestion",
        "Compressed headways, slow progress, and intermittent pedestrian pressure.",
        "intersection-v0",
        "urban_junction",
        traffic_density=(0.75, 1.00),
        aggressiveness_mix={"normal": 0.28, "erratic": 0.16, "opportunistic": 0.18, "defensive": 0.14, "aggressive": 0.14, "conservative": 0.10},
        hazard_density=(0.08, 0.18),
        pedestrian_frequency=(0.18, 0.40),
        pothole_density=(0.03, 0.12),
        visibility=(0.75, 1.00),
        friction=(0.82, 1.00),
        obstacle_density=(0.04, 0.12),
        tags=("urban", "congestion"),
    ),
    "narrow_road_negotiation": _preset(
        "narrow_road_negotiation",
        "Narrow road negotiation",
        "Tight corridor with reduced maneuvering space and opposing negotiation pressure.",
        "highway-v0",
        "narrow_corridor",
        traffic_density=(0.35, 0.72),
        aggressiveness_mix={"defensive": 0.20, "normal": 0.22, "opportunistic": 0.20, "aggressive": 0.15, "erratic": 0.13, "conservative": 0.10},
        hazard_density=(0.10, 0.24),
        pedestrian_frequency=(0.03, 0.12),
        pothole_density=(0.05, 0.16),
        visibility=(0.72, 1.00),
        friction=(0.82, 1.00),
        obstacle_density=(0.08, 0.18),
        lane_count=(2, 2),
        tags=("corridor", "narrow"),
    ),
    "blind_intersection_occlusion": _preset(
        "blind_intersection_occlusion",
        "Blind intersection with occlusion",
        "Occluding roadside objects reduce visibility near the conflict zone.",
        "intersection-v0",
        "occluded_intersection",
        traffic_density=(0.45, 0.85),
        aggressiveness_mix={"normal": 0.22, "aggressive": 0.18, "opportunistic": 0.20, "defensive": 0.14, "erratic": 0.16, "conservative": 0.10},
        hazard_density=(0.12, 0.28),
        pedestrian_frequency=(0.12, 0.30),
        pothole_density=(0.00, 0.08),
        visibility=(0.45, 0.80),
        friction=(0.82, 1.00),
        obstacle_density=(0.10, 0.20),
        tags=("junction", "occlusion"),
    ),
    "erratic_taxi_behavior": _preset(
        "erratic_taxi_behavior",
        "Erratic taxi behavior",
        "Taxi-heavy flow with abrupt stops and aggressive lane changes.",
        "highway-v0",
        "urban_corridor",
        traffic_density=(0.42, 0.80),
        aggressiveness_mix={"erratic": 0.24, "opportunistic": 0.20, "normal": 0.18, "aggressive": 0.18, "defensive": 0.10, "conservative": 0.10},
        hazard_density=(0.05, 0.15),
        pedestrian_frequency=(0.10, 0.25),
        pothole_density=(0.02, 0.10),
        visibility=(0.78, 1.00),
        friction=(0.84, 1.00),
        obstacle_density=(0.04, 0.12),
        tags=("urban", "taxi"),
    ),
    "aggressive_tailgater": _preset(
        "aggressive_tailgater",
        "Aggressive tailgater scenario",
        "Fast followers maintain unsafe headways and pressure slower leaders.",
        "highway-v0",
        "corridor",
        traffic_density=(0.38, 0.75),
        aggressiveness_mix={"aggressive": 0.34, "opportunistic": 0.22, "normal": 0.18, "erratic": 0.12, "defensive": 0.08, "conservative": 0.06},
        hazard_density=(0.03, 0.10),
        pedestrian_frequency=(0.00, 0.03),
        pothole_density=(0.01, 0.08),
        visibility=(0.82, 1.00),
        friction=(0.85, 1.00),
        obstacle_density=(0.01, 0.06),
        tags=("corridor", "tailgater"),
    ),
    "pedestrian_hesitation_conflict": _preset(
        "pedestrian_hesitation_conflict",
        "Pedestrian hesitation conflict",
        "Pedestrians with fluctuating crossing intent create ambiguous right-of-way.",
        "intersection-v0",
        "crosswalk",
        traffic_density=(0.35, 0.68),
        aggressiveness_mix={"defensive": 0.16, "normal": 0.20, "conservative": 0.16, "opportunistic": 0.18, "aggressive": 0.16, "erratic": 0.14},
        hazard_density=(0.06, 0.16),
        pedestrian_frequency=(0.30, 0.75),
        pothole_density=(0.00, 0.06),
        visibility=(0.78, 1.00),
        friction=(0.84, 1.00),
        obstacle_density=(0.02, 0.08),
        tags=("pedestrian", "hesitation"),
    ),
    "mixed_vehicle_types": _preset(
        "mixed_vehicle_types",
        "Mixed vehicle types traffic",
        "Cars, vans, trucks, taxis, and motorcycles share the same corridor.",
        "highway-v0",
        "corridor",
        traffic_density=(0.42, 0.82),
        aggressiveness_mix={"normal": 0.22, "opportunistic": 0.20, "aggressive": 0.18, "defensive": 0.14, "conservative": 0.12, "erratic": 0.14},
        hazard_density=(0.04, 0.12),
        pedestrian_frequency=(0.00, 0.04),
        pothole_density=(0.02, 0.10),
        visibility=(0.80, 1.00),
        friction=(0.84, 1.00),
        obstacle_density=(0.03, 0.10),
        tags=("corridor", "mixed_fleet"),
    ),
    "double_parking_obstruction": _preset(
        "double_parking_obstruction",
        "Double parking obstruction",
        "Roadside parked obstacles constrict the corridor and trigger lane negotiation.",
        "highway-v0",
        "urban_corridor",
        traffic_density=(0.35, 0.72),
        aggressiveness_mix={"normal": 0.22, "opportunistic": 0.22, "aggressive": 0.18, "defensive": 0.14, "conservative": 0.12, "erratic": 0.12},
        hazard_density=(0.10, 0.24),
        pedestrian_frequency=(0.06, 0.18),
        pothole_density=(0.01, 0.08),
        visibility=(0.76, 1.00),
        friction=(0.84, 1.00),
        obstacle_density=(0.14, 0.30),
        tags=("urban", "obstruction"),
    ),
    "construction_zone_traffic": _preset(
        "construction_zone_traffic",
        "Construction zone traffic",
        "Temporary work-zone barriers, narrowed lanes, and disrupted flow.",
        "merge-v0",
        "construction",
        traffic_density=(0.32, 0.68),
        aggressiveness_mix={"normal": 0.20, "defensive": 0.18, "opportunistic": 0.20, "aggressive": 0.16, "erratic": 0.14, "conservative": 0.12},
        hazard_density=(0.18, 0.35),
        pedestrian_frequency=(0.02, 0.08),
        pothole_density=(0.03, 0.14),
        visibility=(0.70, 0.98),
        friction=(0.80, 0.98),
        obstacle_density=(0.18, 0.34),
        tags=("construction", "merge"),
    ),
    "rain_low_friction": _preset(
        "rain_low_friction",
        "Rain or low friction environment",
        "Reduced friction, degraded visibility, and more conservative braking requirements.",
        "highway-v0",
        "wet_corridor",
        traffic_density=(0.28, 0.70),
        aggressiveness_mix={"defensive": 0.20, "normal": 0.24, "opportunistic": 0.18, "aggressive": 0.14, "conservative": 0.14, "erratic": 0.10},
        hazard_density=(0.04, 0.12),
        pedestrian_frequency=(0.02, 0.10),
        pothole_density=(0.08, 0.22),
        visibility=(0.40, 0.78),
        friction=(0.45, 0.78),
        obstacle_density=(0.03, 0.10),
        tags=("weather", "low_friction"),
    ),
    "multi_vehicle_negotiation_junction": _preset(
        "multi_vehicle_negotiation_junction",
        "Multi-vehicle negotiation junction",
        "Several agents simultaneously negotiate the same conflict area.",
        "intersection-v0",
        "junction",
        traffic_density=(0.60, 0.95),
        aggressiveness_mix={"normal": 0.20, "opportunistic": 0.22, "aggressive": 0.18, "erratic": 0.18, "defensive": 0.12, "conservative": 0.10},
        hazard_density=(0.06, 0.18),
        pedestrian_frequency=(0.08, 0.22),
        pothole_density=(0.00, 0.06),
        visibility=(0.74, 1.00),
        friction=(0.82, 1.00),
        obstacle_density=(0.04, 0.12),
        tags=("junction", "negotiation"),
    ),
    "dense_urban_chaos": _preset(
        "dense_urban_chaos",
        "Dense urban chaos scenario",
        "Composite high-density urban environment with pedestrians, hazards, mixed drivers, and obstructed flow.",
        "intersection-v0",
        "urban_chaos",
        traffic_density=(0.72, 1.00),
        aggressiveness_mix={"normal": 0.18, "aggressive": 0.18, "opportunistic": 0.18, "erratic": 0.18, "defensive": 0.14, "conservative": 0.14},
        hazard_density=(0.18, 0.38),
        pedestrian_frequency=(0.22, 0.60),
        pothole_density=(0.08, 0.25),
        visibility=(0.50, 0.95),
        friction=(0.65, 1.00),
        obstacle_density=(0.10, 0.24),
        tags=("urban", "chaos", "composite"),
    ),
}
